version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - checkout
      # Bundle install dependencies
      - run: npm install
      - run: node hello.js
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "1 * * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - build
