version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: node hello.js
nightly:
  triggers:
    - schedule:
        cron: "1 * * * *"
        filters:
          branches:
            only:
              - master
  # — checkout
  # - run: npm install

  # — run: npm test
