version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    working_directory: ~/repo
    steps:
      - checkout
      # Bundle install dependencies
      # - run:
      #     name: "Setup custom environment variables"
      - run:
          name: "What was my custom environment variable?"
          command: echo ${BQ_KEY}
      - run: npm install
      # - run: node hello.js
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    # jobs:
    #   - build
    triggers:
      - schedule:
          cron: "0,30 * * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - build
